ballerina-platform/asyncapi-triggers

.github/workflows/ci.yml
.github/workflows/release.yml

Add packageUser and packagePAT

Add envs to the workflows

---

.github/workflows/ci.yml

Change CI workflow ballerina version from nightly build to beta6

Change CI workflow ballerina version

---

asyncapi/gmail/Module.md
asyncapi/gmail/Package.md

Update Module and Package md files

---

.github/workflows/release.yml

Modify release pipeline to on workflow_dispatch

---

asyncapi/google.calendar/Dependencies.toml

Update calendar connector version

Update calendar connector version

---

.github/workflows/ci.yml

Update git workflow

---

.github/workflows/daily_build.yml

Add daily build workflow to test the trigger builds with the latest Ballerina nightly builds

Add daily build workflow

---

asyncapi/google.drive/Module.md
asyncapi/google.drive/Package.md
asyncapi/google.drive/data_types.bal
asyncapi/google.drive/dispatcher_service.bal
asyncapi/google.drive/listener.bal
asyncapi/google.drive/watch_scheduler.bal

Related to https://github.com/wso2-enterprise/choreo/issues/10771

Add Module.md file to Google Drive trigger

---

.github/workflows/ci.yml
asyncapi/google.drive/Ballerina.toml
asyncapi/google.drive/Dependencies.toml
asyncapi/google.drive/Package.md
asyncapi/google.mail/Ballerina.toml
asyncapi/google.mail/Dependencies.toml
asyncapi/google.mail/Package.md
asyncapi/google.sheets/Ballerina.toml
asyncapi/google.sheets/Dependencies.toml
asyncapi/google.sheets/Package.md

Related to https://github.com/wso2-enterprise/choreo/issues/11762

Trigger version bump for ballerina 2201.0.1

---

asyncapi/github/Ballerina.toml
asyncapi/github/Dependencies.toml
asyncapi/github/Package.md
asyncapi/google.calendar/Ballerina.toml
asyncapi/google.calendar/Dependencies.toml
asyncapi/google.calendar/Package.md
asyncapi/google.calendar/data_types.bal
asyncapi/slack/Ballerina.toml
asyncapi/slack/Dependencies.toml
asyncapi/slack/Package.md

Update github gcal and slack to latest dist

Update github gcal and slack to latest dist

---

.github/workflows/prod_release.yml

Update release pipeline Ballerina version to 2201.0.1

---

.github/workflows/dev_stage_release.yml
.github/workflows/prod_release.yml

$subject
Related to: https://github.com/wso2-enterprise/choreo/issues/12258

Add dev/stage release pipelines

---

asyncapi/asb/Dependencies.toml
asyncapi/github/Dependencies.toml
asyncapi/github/asyncapi.yml
asyncapi/github/data_types.bal
asyncapi/github/dispatcher_service.bal
asyncapi/github/listener.bal
asyncapi/github/service_types.bal
asyncapi/google.calendar/Dependencies.toml
asyncapi/google.drive/Dependencies.toml
asyncapi/google.mail/Dependencies.toml
asyncapi/google.sheets/Dependencies.toml

Related https://github.com/wso2-enterprise/choreo/issues/12345

Add github project_card event

---

asyncapi/github/service_types.bal

Add doc comments to the Github service types

---

asyncapi/twilio/tests/twilio_callTest.bal
asyncapi/twilio/tests/twilio_smsTest.bal

Related https://github.com/wso2-enterprise/choreo/issues/12709

Add twilio unit tests

---

asyncapi/github/Ballerina.toml
asyncapi/github/Dependencies.toml
asyncapi/github/data_types.bal

> This fixes the issue that occurred due to error in mapping the received payload to record types which represent events.
Fixes https://github.com/wso2-enterprise/choreo/issues/12958

Update records used for data mapping

---

asyncapi/google.mail/Ballerina.toml
asyncapi/google.mail/Dependencies.toml
asyncapi/google.mail/util.bal

> This fixes the issue that occurred due to an error in mapping the error into custom error messages by returning the exact error itself
Fixes https://github.com/wso2-enterprise/choreo/issues/13072

Fix Gmail trigger error mapping issue

---

asyncapi/twilio/data_types.bal
asyncapi/twilio/listener.bal
asyncapi/twilio/tests/twilio_callTest.bal
asyncapi/twilio/tests/twilio_smsTest.bal

Related https://github.com/wso2-enterprise/choreo/issues/13017

Remove listenerConfig from init function[Twilio]

---

asyncapi/twilio/Ballerina.toml
asyncapi/twilio/Dependencies.toml
asyncapi/twilio/Module.md
asyncapi/twilio/Package.md

Related https://github.com/wso2-enterprise/choreo/issues/11866

Update Twilio Package.md and Module.md files

---

asyncapi/asb/service_types.bal
asyncapi/github/service_types.bal
asyncapi/google.calendar/service_types.bal
asyncapi/google.drive/service_types.bal
asyncapi/google.mail/service_types.bal
asyncapi/google.sheets/service_types.bal
asyncapi/salesforce/listener.bal
asyncapi/salesforce/service_types.bal
asyncapi/salesforce/tests/listener_test.bal
asyncapi/slack/dispatcher_service.bal
asyncapi/slack/listener.bal
asyncapi/slack/service_types.bal
asyncapi/slack/tests/tests.bal

> To add a description for each service type, this will help the end users to understand the content of each service type
> These descriptions will be shown in the UI as below ( Descriptions will replace the "Lorem ipsum dolor..." )
> https://github.com/wso2-enterprise/choreo/issues/12848

Add doc comments

---

.github/workflows/dev_stage_release.yml

Update workflow to get bal dist version

Update workflow to get bal dist version

---

asyncapi/salesforce/.gitignore
asyncapi/salesforce/Ballerina.toml
asyncapi/salesforce/Dependencies.toml
asyncapi/salesforce/Module.md
asyncapi/salesforce/Package.md
asyncapi/salesforce/data_types.bal
asyncapi/salesforce/listener.bal
gradle.properties
native/sfdc/src/main/java/io/ballerina/sfdc/Constants.java
native/sfdc/src/main/java/io/ballerina/sfdc/ListenerUtil.java
native/sfdc/src/main/java/io/ballerina/sfdc/LoginHelper.java

$subject
Fixes: https://github.com/ballerina-platform/ballerina-extended-library/issues/451
> The sandbox orgs are not supported to login in the current implementation
> Fixed enabling the sandbox login URL
- Unit tests 
> Code coverage information
- Integration tests
> Details about the test cases and coverage
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
> Provide high-level details about the samples related to this feature
> List any other related PRs
> Describe migration …

Fix the issue in calling trigger in sandbox environments

---

.github/workflows/dev_stage_release.yml

Add bal dist version field to workflow

---

.github/workflows/dev_stage_release.yml
build.gradle

Add specific trigger release support to workflows

Add specific trigger release support to workflows

---

build.gradle

Add specific trigger dir check

Add specific trigger directory check

---

asyncapi/aayu.mftg.as2/Ballerina.toml
asyncapi/aayu.mftg.as2/Dependencies.toml
asyncapi/github/Ballerina.toml
asyncapi/github/Dependencies.toml
asyncapi/google.calendar/Ballerina.toml
asyncapi/google.calendar/Dependencies.toml
asyncapi/google.calendar/utils.bal
asyncapi/google.drive/Ballerina.toml
asyncapi/google.drive/Dependencies.toml
asyncapi/google.mail/Ballerina.toml
asyncapi/google.mail/Dependencies.toml
asyncapi/google.sheets/Ballerina.toml
asyncapi/google.sheets/Dependencies.toml
asyncapi/shopify/Ballerina.toml
asyncapi/shopify/Dependencies.toml
asyncapi/slack/Ballerina.toml
asyncapi/slack/Dependencies.toml
asyncapi/twilio/Ballerina.toml
asyncapi/twilio/Dependencies.toml

Migrate http triggers to Ballerina SwanLake 2201.1.1
Issue - https://github.com/wso2-enterprise/choreo/issues/14128
Migrate http triggers to Ballerina SwanLake 2201.1.1

Migrate http triggers to Ballerina SwanLake 2201.1.1

---

asyncapi/hubspot/asyncapi.yaml
asyncapi/hubspot/data_types.bal
asyncapi/hubspot/dispatcher_service.bal
asyncapi/hubspot/service_types.bal
asyncapi/hubspot/tests/tests.bal

Related https://github.com/wso2-enterprise/choreo/issues/15414

Fix record type issue

---

asyncapi/asgardeo/dispatcher_service.bal
asyncapi/asgardeo/listener.bal

Add logs and remove hub secret from the listener

---

.github/workflows/ci.yml
.github/workflows/dev_stage_release.yml
.github/workflows/prod_release.yml

Update workflows to support ballerina 2201.2.1
Issue - https://github.com/wso2-enterprise/choreo/issues/15821

Update workflows to support ballerina 2201.2.1

---

asyncapi/asgardeo/Ballerina.toml
asyncapi/asgardeo/Dependencies.toml

Remove asgardeo trigger icon temporarily, due to an issue in Ballerina DEV central

---

asyncapi/asgardeo/Ballerina.toml
asyncapi/asgardeo/listener.bal

Revert removing icon and change a service type name

---

asyncapi/asgardeo/data_types.bal
asyncapi/asgardeo/listener.bal

Remove hub secret from listener configs and add a unique hash for that

---

asyncapi/aayu.mftg.as2/Ballerina.toml
asyncapi/asb/Ballerina.toml
asyncapi/asgardeo/Ballerina.toml
asyncapi/github/Ballerina.toml
asyncapi/github/data_types.bal
asyncapi/google.calendar/Ballerina.toml
asyncapi/google.drive/Ballerina.toml
asyncapi/google.mail/Ballerina.toml
asyncapi/google.sheets/Ballerina.toml
asyncapi/hubspot/Ballerina.toml
asyncapi/quickbooks/Ballerina.toml
asyncapi/salesforce/Ballerina.toml
asyncapi/shopify/Ballerina.toml
asyncapi/slack/Ballerina.toml
asyncapi/twilio/Ballerina.toml

Migrate triggers to ballerina 2201.2.3
Issue - https://github.com/wso2-enterprise/choreo/issues/15821

Migrate triggers to ballerina 2201.2.3

---

asyncapi/asgardeo/data_types.bal

Add additional claims attribute to events in Asgardeo trigger

---

asyncapi/aayu.mftg.as2/Package.md
asyncapi/asb/Package.md
asyncapi/asgardeo/Package.md
asyncapi/github/Package.md
asyncapi/google.calendar/Package.md
asyncapi/google.drive/Package.md
asyncapi/google.mail/Package.md
asyncapi/google.sheets/Package.md
asyncapi/hubspot/Package.md
asyncapi/quickbooks/Package.md
asyncapi/salesforce/Package.md
asyncapi/shopify/Package.md
asyncapi/slack/Package.md
asyncapi/twilio/Package.md

Refactor Slack to Discord

---

asyncapi/asgardeo/Module.md
asyncapi/asgardeo/Package.md

> Add documentations for Asgardeo Trigger.
> Update module.md & Package.md

Add documentations for Asgardeo Trigger.

---

asyncapi/asgardeo/Ballerina.toml
asyncapi/asgardeo/Dependencies.toml
asyncapi/asgardeo/data_types.bal
asyncapi/asgardeo/dispatcher_service.bal
asyncapi/asgardeo/listener.bal
asyncapi/asgardeo/utils.bal
build.gradle
gradle.properties
native/asgardeo/build.gradle
native/asgardeo/src/main/java/io/crypto/Decryption.java
native/asgardeo/src/main/java/io/crypto/Utils.java
settings.gradle

> Decrypt payload in asgardeo trigger
Related PRs
1. Crypto key service
https://github.com/wso2-enterprise/choreo-crypto-key-service/pull/1
2. Payload decryption in Asgardeo trigger
https://github.com/ballerina-platform/asyncapi-triggers/pull/127/
3. Deployment-related PRs
https://github.com/wso2-enterprise/choreo-cp-env-overlay/pull/6499 
https://github.com/wso2-enterprise/choreo-control-plane/pull/6137 
4. Choreo Console PR
https://github.com/wso2-enterprise/choreo-console/pull/6502
Improvement : https://github.com/wso2-enterprise/choreo/issues/16830
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, …

add payload decryption functionality

---

asyncapi/asgardeo/data_types.bal
asyncapi/asgardeo/dispatcher_service.bal

> Update record parameter IV to ivParameterSpec
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

update record parameter IV to ivParameterSpec

---

.gitignore
asyncapi/salesforce/.gitignore
asyncapi/salesforce/Ballerina.toml
asyncapi/salesforce/Dependencies.toml
asyncapi/salesforce/Module.md
asyncapi/salesforce/data_types.bal
asyncapi/salesforce/listener.bal
gradle.properties
native/sfdc/src/main/java/io/ballerina/sfdc/Constants.java
native/sfdc/src/main/java/io/ballerina/sfdc/ListenerUtil.java
native/sfdc/src/main/java/io/ballerina/sfdc/LoginHelper.java

$subject
Fixes: https://github.com/ballerina-platform/ballerina-extended-library/issues/451
> The sandbox orgs are not supported to login in the current implementation
> Fixed enaling the sandbox login URL
- Unit tests 
> Tested with the WSO2 Sandbox
- Integration tests
> Details about the test cases and coverage
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Provide high-level details about the samples related to this feature
> …

Add improvement to support to use Salesforce Sandbox accounts

---

asyncapi/asb/dispatcher_service.bal

Add dummy dispatcher_service file to check in central APIs

Add dummy dispatcher_service file to check in central APIs

---

asyncapi/asb/Ballerina.toml

Update ASB version to support central listing

Update ASB version to support central listing

---

asyncapi/asb/Ballerina.toml
asyncapi/asb/Module.md

$subject. 
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/553

Fix quick-start documentation in ASB trigger module

---

asyncapi/asb/Ballerina.toml
asyncapi/asb/listener.bal

Change ASB listnerParam name to support BC trigger API

Change ASB listnerParam name to support BC trigger API

---

asyncapi/github/data_types.bal

Fixes https://github.com/ballerina-platform/ballerina-library/issues/5897
> Link to the PR for changes to the training content in …

[GitHub Trigger] Mark email field of the user record as nilable

---

asyncapi/asgardeo/Ballerina.toml
asyncapi/asgardeo/Dependencies.toml

Update dependency versions

---

asyncapi/asgardeo/Module.md
asyncapi/asgardeo/asyncapi.yml
asyncapi/asgardeo/data_types.bal
asyncapi/asgardeo/dispatcher_service.bal
asyncapi/asgardeo/service_types.bal

> Add login success and login failed event.
[https://github.com/wso2-enterprise/asgardeo-extensions/pull/229](https://www.google.com/url?q=https://github.com/wso2-enterprise/asgardeo-extensions/pull/229&sa=D&source=calendar&ust=1707041976587724&usg=AOvVaw00zF_ZvSLDj9MZD9BVeMaM)
https://github.com/wso2-enterprise/iam-engineering/issues/963

Add login success attribute and login failed event

---

asyncapi/asgardeo/asyncapi.yml
asyncapi/asgardeo/data_types.bal
asyncapi/asgardeo/dispatcher_service.bal
asyncapi/asgardeo/service_types.bal

> Improve Credentials Update Event
https://github.com/wso2-enterprise/iam-engineering/issues/963

Improve Credentials Update Event

---

asyncapi/asgardeo/asyncapi.yml
asyncapi/asgardeo/data_types.bal

Add new properties to credential update

---

.github/workflows/dev_stage_release.yml
.github/workflows/prod_release.yml

Remove `git` installation step from the release workflows

---

.github/workflows/dev_stage_release.yml
asyncapi/github/Dependencies.toml
asyncapi/google.sheets/Dependencies.toml
asyncapi/quickbooks/Dependencies.toml
asyncapi/shopify/Dependencies.toml

Update dev/stage publish workflows

---

.github/workflows/ci.yml
.github/workflows/daily_build.yml
.github/workflows/dev_stage_release.yml
.github/workflows/prod_release.yml

Bump ballerina version in the workflows
